name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      
  deploy:
    needs: build
    runs-on: ununtu-latest
    steps:
    - name: dotnet build and publish
      run: dotnet restore
    - name: build config 
      run: dotnet build --configuration Release
    - name: Publish release      
      run: dotnet publish -c Release -o /myapp 
          
    - name: 'Run Azure webapp deploy action using publish profile credentials'
    - uses: azure/webapps-deploy@v2
      with: 
          app-name: geodemotesting # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET  }} # Define secret variable in repository settings as per action documentation
          package: /myapp
